### PR TITLE
Add ports for gps and position-reset to the UWPoseEstimator-Task

### PR DESCRIPTION
**Pull request by fzachert**
I added two additional ports for gps-input and reseting the position, based on an external reference, to the UWPoseEstimatior-Task. The position-reset can be done by using the input-port or a defined operation

### CODE REVIEW

**Comment by saarnold** [comment]
There is already an operator to reset the pose and also the filter named resetState().
Since it resets the filter to the pose set by initial_state, I would also avoid to have a reset 'input port'. Is there any use case where the property is not enough?

**Comment by fzachert** [comment]
resetState() resets the whole filter, including the orientation and velocity.
There could be the case, that I only want to set the position, but keep the orientation or depth.
If you have multiple external features for reseting the filter, an input-port is usefull, because you can specify the position for the reset.
But i agree, that the reset_to_origin-operation is redundant

**Comment by saarnold** [comment]
Reseting the filter would be the right thing to do if you want reset / jump to a certain state.
The rest would be filter update steps, and here you cannot guarantee that the pose of the filter will be set to the one of your input sample. The error of the filter could be smaller, because of some other measurement.
Why not using an existing port to send an additional measurement with a small covariance?

**Comment by fzachert** [comment]
You are right, the velocity/orientation is only used for the update-step.
I could also use an existing port to send measurements with a small covariance for the setting-operation.
So I would sugest: throw away the reset-inputport and the reset-to-origin-operation, but keep the new gps-port

**Comment by saarnold** [comment]
Ok, sound good.

**Comment by fzachert** [comment]
I added also a port for positions, which where estimated by a camera and visual markers. The sample contains a 3D-position.
Are you fine with merging this?

**Comment by fzachert** [comment]
Renamed the camera_position_samples-port to xyz_position_samples

**Comment by saarnold** [comment]
Is there a need for the xyz_position2body transformation? It makes sense for devices since they are normally not in the body frame. Pose updates coming from higher level components, I would assume, are anyway in the body frame.

**Comment by fzachert** [comment]
In my case, the position is in the camera frame, but I could add a transformation to my external locazation module so that the sample is in body frame. So there is no need for a xyz_positon2body transformation

**Comment by fzachert** [comment]
Removed the xyz_positon2body transformation

**Comment by saarnold** [comment]
Ok thanks

**Pull request merged**
